FORMAT: 1A
HOST: https://us-central1-devconnector-cc2ce.cloudfunctions.net/app/api

# Posts 

Testing Posts API

## Posts [/posts]

### Create Post [POST]

+ Request (application/json)
    
    + Headers
    
            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ii1MS2VTcm1oMGd2aV9vRWxxamV1IiwibmFtZSI6ImhlbGxvIiwiYXZhdGFyIjoiLy93d3cuZ3JhdmF0YXIuY29tL2F2YXRhci82Mjc2ZGIzNTU1YWU2Zjc4ZWM5Yzc3NDQ1NzdiNGJkYT9zPTIwMCZyPXBnJmQ9bW0iLCJlbWFpbCI6ImFiY2FiY2FiY0BnbWFpbC5jb20iLCJpYXQiOjE1MzUxODA4MDAsImV4cCI6MTUzNTE4NDQwMH0.CYwyM1ryti-032SW2qcDFbBSTAxxG5OrBBcCiTGt-Ns
    
    + Body
    
            {
                "text": "This is a testing post 25Aug 15:35"
            }

+ Response 200 (application/json; charset=utf-8)

